#!/usr/bin/env python3
"""Emit state_table.cpp: every storage member of the verilated model outside
the CPU, by hierarchical name, for portable snapshots (snapshot.cpp).

Verilator keeps each variable as a C++ member named after its hierarchy
(`__PVT__pic__DOT__imr`). A snapshot saves these by name; a restore into a
rebuilt model copies back those whose name and size still match. The CPU
(`z486_cpu`) is left out: its architectural state is restored separately and
its microarchitecture starts from reset, so CPU changes don't invalidate a
snapshot.

usage: gen_state_table.py <obj_dir> <prefix> <output.cpp>
"""
import re
import sys
from pathlib import Path

obj_dir, prefix, out_path = Path(sys.argv[1]), sys.argv[2], Path(sys.argv[3])

MEMBER = re.compile(
    r"^\s*(?:CData|SData|IData|QData|EData|VlWide<\d+>|VlUnpacked<.*>)(?:/\*[^*]*\*/)?\s+(\w+);\s*$")
PORT = re.compile(r"^\s*VL_(?:IN|OUT|INOUT)(?:8|16|64|W)?\((\w+),")
# Scheduler bookkeeping that is not design state.
SKIP = re.compile(r"z486_cpu|^__V(?:stl|ico|act|nba|m_|Didinit|DidInit)|IterCount")


def members(header):
    names = []
    for line in header.read_text().splitlines():
        m = MEMBER.match(line) or PORT.match(line)
        if m and not SKIP.search(m.group(1)):
            names.append(m.group(1))
    return names


def class_header(cls):
    return obj_dir / f"{cls}.h"


root_cls = f"{prefix}___024root"
# The instance tree: root -> top module -> its submodule objects. Follow
# pointer members whose type is another class of this model.
ptr = re.compile(rf"^\s*({prefix}_\w+)\*\s+(\w+);\s*$")
classes = []          # (C++ access expression, class name, scope label)
todo = [("r", root_cls, "TOP")]
while todo:
    expr, cls, label = todo.pop()
    classes.append((expr, cls, label))
    for line in class_header(cls).read_text().splitlines():
        m = ptr.match(line)
        if m and m.group(1) != f"{prefix}__Syms":
            todo.append((f"{expr}->{m.group(2)}", m.group(1), f"{label}.{m.group(2)}"))

lines = [
    "// Generated by gen_state_table.py; do not edit.",
    '#include "../snapshot.h"',
    f'#include "{prefix}.h"',
]
lines += [f'#include "{cls}.h"' for _, cls, _ in classes]
lines += [
    "",
    f"void snapshot_state_table({prefix}* tb, std::vector<SnapshotField>& out) {{",
    "    auto* r = tb->rootp;",
]
count = 0
for expr, cls, label in classes:
    for name in members(class_header(cls)):
        lines.append(f'    out.push_back({{"{label}.{name}", &{expr}->{name}, sizeof({expr}->{name})}});')
        count += 1
lines.append("}")
out_path.write_text("\n".join(lines) + "\n")
print(f"gen_state_table: {count} fields in {len(classes)} classes -> {out_path}")
